services:
  ContaoThemeManager\Core\Migration\ContentElementsMigration:
    arguments:
      - '@database_connection'
      - '@contao.framework'
    tags:
      - { name: contao.migration, priority: 0 }

  ContaoThemeManager\Core\Migration\ThemeConfigurationMigration:
    arguments:
      - '@database_connection'
      - '@contao.framework'
    tags:
      - { name: contao.migration, priority: 0 }
